# Listen for incoming network connection on the specified port
listener 1883
protocol mqtt

# Require clients to provide a valid username and password from the password file
allow_anonymous false
password_file /mosquitto/config/passwords

# Limit the total number of clients connected for the current listener
max_connections -1
