# Listen for incoming ssl network connection on the specified port
listener 8883
protocol mqtt
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key

# On zigbee2mqtt, use mqtts://mosquitto:8883 as the broker URL to connect securely to Mosquitto using TLS.
# On matterbridge, use mqtts://localhost as host and 8883 as port to connect securely to Mosquitto using TLS.
# On zigbee2mqtt and matterbridge, use /mosquitto/certs/ca.crt as the CA certificate, /mosquitto/certs/client.crt as the client certificate, and /mosquitto/certs/client.key as the client key. Enable reject unauthorized to ensure the server certificate is verified.

# Require clients to provide a valid username and password from the password file
allow_anonymous false
password_file /mosquitto/config/passwords

# Limit the total number of clients connected for the current listener
max_connections -1
