# Docker: create the directory for the socket file and set permissions so that the mosquitto user can read/write to it.
# sudo mkdir -p "/mosquitto/run"
# sudo chown 1883:1883 "/mosquitto/run"
# sudo chmod 770 "/mosquitto/run"
#
# Add volume mapping for the run directory in the docker-compose.yml file:
# - "${HOME}/mosquitto/run:/var/run/mosquitto"

# Unix socket listener
listener 0 /var/run/mosquitto/mqtt.sock
protocol mqtt

# Require clients to provide a valid username and password from the password file
allow_anonymous false
password_file /mosquitto/config/passwords

# Limit the total number of clients connected for the current listener
max_connections -1
