# Listen for incoming websocket network connection on the specified port
listener 9001
protocol websockets

# Require clients to provide a valid username and password from the password file
allow_anonymous false
password_file /mosquitto/config/passwords

# Limit the total number of clients connected for the current listener
max_connections -1
