# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

pid_file /mosquitto/data/mosquitto.pid

# If true, connection, subscription and message data will be written to the disk in mosquitto.db at the location dictated by persistence_location
persistence true
# The path where the persistence database should be stored
persistence_location /mosquitto/data
# This option allows the session of persistent clients (those with clean session set to false) that are not currently connected to be 
# removed if they do not reconnect within a certain time frame.
# persistent_client_expiration 1d

# QoS 1 and 2 messages will be allowed inflight per client until this limit
# is exceeded.  Defaults to 0. (No maximum)
# See also max_inflight_messages
max_inflight_bytes 0

# The maximum number of QoS 1 and 2 messages currently inflight per
# client.
# This includes messages that are partway through handshakes and
# those that are being retried. Defaults to 20. Set to 0 for no
# maximum. Setting to 1 will guarantee in-order delivery of QoS 1
# and 2 messages.
#max_inflight_messages 20
max_inflight_messages 1000
max_queued_messages 1000

# The number of seconds that mosquitto will wait between each time it saves the in-memory database to disk
autosave_interval 60

# The log will include entries when clients connect and disconnect
connection_messages true

# Send log messages to a particular destination. Possible destinations are: stdout stderr syslog topic file dlt
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Boolean value, if set to true a timestamp value will be added to each log entry
log_timestamp true

# Set the format of the log timestamp
log_timestamp_format %Y-%m-%dT%H:%M:%S

# Choose types of messages to log
log_type error
log_type warning
log_type notice
log_type information
# log_type debug
log_type subscribe
log_type unsubscribe
connection_messages true

# External configuration files may be included by using the include_dir option
include_dir /mosquitto/config/conf.d
