name: Node.js CI

on:
  push:
    paths-ignore:
      - '**/*.md' # any .md anywhere
  pull_request:
    paths-ignore:
      - '**/*.md' # any .md anywhere
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Verify Node.js version
        run: node -v

      - name: Verify Npm version
        run: npm -v

      - name: Select matterbridge branch
        id: select_matterbridge_ref
        shell: pwsh
        run: |
          $ref = if ('${{ github.event_name }}' -eq 'push') { 'dev' } else { 'main' }
          "ref=$ref" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Clone matterbridge repo branch ${{ steps.select_matterbridge_ref.outputs.ref }}
        run: git clone --depth 1 --single-branch --no-tags -b ${{ steps.select_matterbridge_ref.outputs.ref }} https://github.com/Luligu/matterbridge.git ../matterbridge

      - name: Install matterbridge dependencies
        working-directory: ../matterbridge
        run: npm ci --no-fund --no-audit

      - name: Build matterbridge
        working-directory: ../matterbridge
        run: npm run build

      - name: Link matterbridge globally
        working-directory: ../matterbridge
        run: npm link --no-fund --no-audit

      - name: Install plugin dependencies
        run: npm ci --no-fund --no-audit

      - name: Link matterbridge in the project
        run: npm link matterbridge --no-fund --no-audit

      - name: Build the plugin
        run: npm run build

      - name: Lint the plugin
        run: npm run lint

      - name: Test the plugin
        run: npm run test -- --forceExit
